[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = apps
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
addopts = --strict-markers -v