# Generated by Django 5.2.1 on 2025-05-25 15:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Le code doit contenir uniquement des lettres majuscules et chiffres')])),
                ('libelle', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('AC', 'Achats'), ('VT', 'Ventes'), ('BQ', 'Banque'), ('CA', 'Caisse'), ('PA', 'Paie et Salaires'), ('FI', 'Fiscal et Déclarations'), ('SO', 'Social'), ('ST', 'Stocks et Inventaires'), ('IM', 'Immobilisations'), ('PR', 'Provisions'), ('AN', 'À nouveaux'), ('CL', 'Clôture'), ('OD', 'Opérations Diverses'), ('EX', 'Extra-comptable')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compte_contrepartie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journaux_contrepartie', to='accounting.compteohada')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journaux',
                'ordering': ['code'],
            },
        ),
    ]
