# Generated by Django 5.2.1 on 2025-05-25 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_journal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciceComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: 2025, 2024', max_length=10, unique=True)),
                ('libelle', models.CharField(help_text='Ex: Exercice 2025', max_length=100)),
                ('date_debut', models.DateField(help_text='Généralement le 01/01/N')),
                ('date_fin', models.DateField(help_text='Généralement le 31/12/N')),
                ('date_cloture_provisoire', models.DateField(blank=True, help_text="Date de clôture provisoire (pour les écritures d'inventaire)", null=True)),
                ('date_cloture_definitive', models.DateField(blank=True, help_text='Date de clôture définitive (max 30/06/N+1)', null=True)),
                ('statut', models.CharField(choices=[('PREPARATION', 'En préparation'), ('OUVERT', 'Ouvert'), ('CLOTURE_PROVISOIRE', 'Clôture provisoire'), ('CLOTURE', 'Clôturé'), ('ARCHIVE', 'Archivé')], default='PREPARATION', max_length=20)),
                ('is_premier_exercice', models.BooleanField(default=False, help_text='Premier exercice de la société')),
                ('report_a_nouveau_genere', models.BooleanField(default=False, help_text='Indique si les À Nouveaux ont été générés')),
                ('date_generation_an', models.DateTimeField(blank=True, help_text='Date de génération des À Nouveaux', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercices_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exercice Comptable',
                'verbose_name_plural': 'Exercices Comptables',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='PeriodeComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(help_text='Numéro du mois (1-12)')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('CLOTUREE', 'Clôturée'), ('VERROUILLEE', 'Verrouillée')], default='OUVERTE', max_length=20)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('cloture_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodes_cloturees', to=settings.AUTH_USER_MODEL)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes', to='accounting.exercicecomptable')),
            ],
            options={
                'verbose_name': 'Période Comptable',
                'verbose_name_plural': 'Périodes Comptables',
                'ordering': ['exercice', 'numero'],
                'unique_together': {('exercice', 'numero')},
            },
        ),
    ]
