# Generated by Django 5.2.1 on 2025-05-25 16:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_exercicecomptable_periodecomptable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code généré automatiquement selon le type', max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^(FLOC|FGRP|CLOC|CGRP|EMPL)\\d{5}$', 'Le code doit être au format : FLOC00001, CGRP00002, etc.')])),
                ('type_tiers', models.CharField(choices=[('FLOC', 'Fournisseur local'), ('FGRP', 'Fournisseur groupe'), ('CLOC', 'Client local'), ('CGRP', 'Client groupe'), ('EMPL', 'Employé')], help_text='Détermine le compte collectif et le préfixe du code', max_length=4)),
                ('raison_sociale', models.CharField(help_text='Dénomination sociale ou nom complet', max_length=200)),
                ('sigle', models.CharField(blank=True, help_text='Sigle ou nom commercial', max_length=50)),
                ('matricule', models.CharField(blank=True, help_text="Matricule de l'employé (si type EMPL)", max_length=20, null=True, unique=True)),
                ('numero_contribuable', models.CharField(blank=True, help_text="Numéro d'identification fiscale", max_length=50, null=True, unique=True)),
                ('rccm', models.CharField(blank=True, help_text='Registre du Commerce (si applicable)', max_length=50)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(default='Cameroun', max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('banque', models.CharField(blank=True, max_length=100)),
                ('numero_compte_bancaire', models.CharField(blank=True, max_length=50)),
                ('delai_paiement', models.PositiveIntegerField(default=30, help_text='Délai de paiement en jours')),
                ('plafond_credit', models.DecimalField(blank=True, decimal_places=0, help_text='Plafond de crédit autorisé (clients uniquement)', max_digits=15, null=True)),
                ('exonere_tva', models.BooleanField(default=False, help_text='Exonéré de TVA')),
                ('contact_principal', models.CharField(blank=True, help_text='Nom du contact principal', max_length=200)),
                ('fonction_contact', models.CharField(blank=True, help_text='Fonction du contact', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Notes internes')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver')),
                ('is_bloque', models.BooleanField(default=False, help_text='Bloquer toute transaction')),
                ('motif_blocage', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compte_collectif', models.ForeignKey(editable=False, help_text='Compte collectif déterminé par le type', on_delete=django.db.models.deletion.PROTECT, related_name='tiers_rattaches', to='accounting.compteohada')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiers_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tiers',
                'verbose_name_plural': 'Tiers',
                'ordering': ['type_tiers', 'code'],
                'indexes': [models.Index(fields=['type_tiers', 'code'], name='accounting__type_ti_99a535_idx')],
            },
        ),
    ]
