# Generated by Django 5.2.1 on 2025-05-25 17:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_tiers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text="Numéro unique de l'écriture (généré automatiquement)", max_length=20, unique=True)),
                ('date_ecriture', models.DateField(help_text="Date de l'écriture comptable")),
                ('date_saisie', models.DateTimeField(auto_now_add=True, help_text='Date et heure de saisie')),
                ('libelle', models.CharField(help_text="Libellé de l'écriture", max_length=200)),
                ('reference_piece', models.CharField(blank=True, help_text='Référence de la pièce justificative', max_length=50)),
                ('type_ecriture', models.CharField(choices=[('NORMALE', 'Écriture normale'), ('CLOTURE', 'Écriture de clôture'), ('OUVERTURE', "Écriture d'ouverture"), ('REGULARISATION', 'Écriture de régularisation'), ('EXTOURNE', "Écriture d'extourne")], default='NORMALE', max_length=20)),
                ('total_debit', models.DecimalField(decimal_places=0, default=0, help_text='Total des débits (calculé automatiquement)', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_credit', models.DecimalField(decimal_places=0, default=0, help_text='Total des crédits (calculé automatiquement)', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée'), ('CLOTUREE', 'Clôturée')], default='BROUILLON', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, help_text="Date de validation de l'écriture", null=True)),
                ('piece_jointe', models.FileField(blank=True, help_text='Pièce justificative scannée', null=True, upload_to='pieces_comptables/%Y/%m/')),
                ('notes', models.TextField(blank=True, help_text='Notes ou commentaires internes')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures_creees', to=settings.AUTH_USER_MODEL)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures', to='accounting.exercicecomptable')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures', to='accounting.journal')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures', to='accounting.periodecomptable')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Écriture Comptable',
                'verbose_name_plural': 'Écritures Comptables',
                'ordering': ['-date_ecriture', '-numero'],
                'permissions': [('valider_ecriture', 'Peut valider une écriture'), ('cloturer_ecriture', 'Peut clôturer une écriture')],
            },
        ),
        migrations.CreateModel(
            name='LigneEcriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=0, default=0, help_text='Montant au débit', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit', models.DecimalField(decimal_places=0, default=0, help_text='Montant au crédit', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('libelle', models.CharField(blank=True, help_text="Libellé spécifique de la ligne (si différent de l'écriture)", max_length=200)),
                ('code_lettrage', models.CharField(blank=True, db_index=True, help_text='Code de lettrage pour rapprochement', max_length=10)),
                ('date_lettrage', models.DateField(blank=True, help_text='Date du lettrage', null=True)),
                ('section_analytique', models.CharField(blank=True, help_text='Code section analytique', max_length=20)),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage dans l'écriture")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compte', models.ForeignKey(help_text='Compte comptable OHADA', on_delete=django.db.models.deletion.PROTECT, related_name='lignes_ecriture', to='accounting.compteohada')),
                ('ecriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='accounting.ecriturecomptable')),
                ('tiers', models.ForeignKey(blank=True, help_text='Tiers concerné (si applicable)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_ecriture', to='accounting.tiers')),
            ],
            options={
                'verbose_name': "Ligne d'écriture",
                'verbose_name_plural': "Lignes d'écriture",
                'ordering': ['ecriture', 'ordre', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='ecriturecomptable',
            index=models.Index(fields=['journal', 'date_ecriture'], name='accounting__journal_65617a_idx'),
        ),
        migrations.AddIndex(
            model_name='ecriturecomptable',
            index=models.Index(fields=['exercice', 'periode'], name='accounting__exercic_edf969_idx'),
        ),
        migrations.AddIndex(
            model_name='ecriturecomptable',
            index=models.Index(fields=['numero'], name='accounting__numero_7db875_idx'),
        ),
        migrations.AddIndex(
            model_name='ligneecriture',
            index=models.Index(fields=['compte', 'ecriture'], name='accounting__compte__34883e_idx'),
        ),
        migrations.AddIndex(
            model_name='ligneecriture',
            index=models.Index(fields=['tiers', 'ecriture'], name='accounting__tiers_i_8ce825_idx'),
        ),
        migrations.AddIndex(
            model_name='ligneecriture',
            index=models.Index(fields=['code_lettrage'], name='accounting__code_le_7a9147_idx'),
        ),
    ]
