# Generated by Django 5.2.1 on 2025-05-25 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_ecriturecomptable_ligneecriture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneecriture',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Montant au crédit', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ligneecriture',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Montant au débit', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
