# Generated by Django 5.2.1 on 2025-05-26 10:10

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_ligneecriture_credit_alter_ligneecriture_debit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecriturecomptable',
            options={'ordering': ['-date_ecriture', '-numero'], 'verbose_name': 'Écriture Comptable', 'verbose_name_plural': 'Écritures Comptables'},
        ),
        migrations.AlterModelOptions(
            name='ligneecriture',
            options={'ordering': ['ecriture', 'numero_ligne'], 'verbose_name': "Ligne d'Écriture", 'verbose_name_plural': "Lignes d'Écriture"},
        ),
        migrations.RemoveIndex(
            model_name='ecriturecomptable',
            name='accounting__numero_7db875_idx',
        ),
        migrations.RemoveIndex(
            model_name='ligneecriture',
            name='accounting__tiers_i_8ce825_idx',
        ),
        migrations.RemoveField(
            model_name='ecriturecomptable',
            name='date_saisie',
        ),
        migrations.RemoveField(
            model_name='ecriturecomptable',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='ecriturecomptable',
            name='piece_jointe',
        ),
        migrations.RemoveField(
            model_name='ecriturecomptable',
            name='reference_piece',
        ),
        migrations.RemoveField(
            model_name='ecriturecomptable',
            name='total_credit',
        ),
        migrations.RemoveField(
            model_name='ecriturecomptable',
            name='total_debit',
        ),
        migrations.RemoveField(
            model_name='ecriturecomptable',
            name='type_ecriture',
        ),
        migrations.RemoveField(
            model_name='ligneecriture',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='ligneecriture',
            name='date_lettrage',
        ),
        migrations.RemoveField(
            model_name='ligneecriture',
            name='debit',
        ),
        migrations.RemoveField(
            model_name='ligneecriture',
            name='ordre',
        ),
        migrations.RemoveField(
            model_name='ligneecriture',
            name='section_analytique',
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='date_piece',
            field=models.DateField(blank=True, help_text='Date de la pièce justificative', null=True),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='is_equilibree',
            field=models.BooleanField(default=False, help_text='Écriture équilibrée (débit = crédit)'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='is_lettree',
            field=models.BooleanField(default=False, help_text='Écriture lettrée'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant total au débit (= crédit si équilibrée)', max_digits=15),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='reference',
            field=models.CharField(blank=True, help_text='Référence externe (numéro facture, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='ligneecriture',
            name='date_echeance',
            field=models.DateField(blank=True, help_text="Date d'échéance pour les tiers", null=True),
        ),
        migrations.AddField(
            model_name='ligneecriture',
            name='date_ligne',
            field=models.DateField(blank=True, help_text="Date spécifique de la ligne (si différente de l'écriture)", null=True),
        ),
        migrations.AddField(
            model_name='ligneecriture',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code devise ISO', max_length=3),
        ),
        migrations.AddField(
            model_name='ligneecriture',
            name='is_lettree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ligneecriture',
            name='montant_credit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant au crédit', max_digits=15),
        ),
        migrations.AddField(
            model_name='ligneecriture',
            name='montant_debit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant au débit', max_digits=15),
        ),
        migrations.AddField(
            model_name='ligneecriture',
            name='numero_ligne',
            field=models.PositiveSmallIntegerField(default=1, help_text="Ordre de la ligne dans l'écriture"),
        ),
        migrations.AddField(
            model_name='ligneecriture',
            name='piece',
            field=models.CharField(blank=True, help_text='Référence pièce (EDF, LOYER, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='date_ecriture',
            field=models.DateField(default=datetime.date.today, help_text="Date de l'écriture comptable"),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='journal',
            field=models.ForeignKey(help_text='Journal comptable (AC, VT, BQ, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='ecritures', to='accounting.journal'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='libelle',
            field=models.CharField(help_text="Libellé général de l'écriture (ex: RELEVES, FACTURE, etc.)", max_length=200),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='numero',
            field=models.CharField(help_text='Numéro automatique : AC240001, VT240002, etc.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée'), ('CLOTUREE', 'Clôturée')], default='BROUILLON', max_length=10),
        ),
        migrations.AlterField(
            model_name='ligneecriture',
            name='code_lettrage',
            field=models.CharField(blank=True, help_text='Code de lettrage pour rapprochement', max_length=10),
        ),
        migrations.AlterField(
            model_name='ligneecriture',
            name='compte',
            field=models.ForeignKey(help_text='Compte du plan OHADA', on_delete=django.db.models.deletion.PROTECT, related_name='lignes_ecritures', to='accounting.compteohada'),
        ),
        migrations.AlterField(
            model_name='ligneecriture',
            name='libelle',
            field=models.CharField(help_text='Libellé de la ligne comptable', max_length=200),
        ),
        migrations.AlterField(
            model_name='ligneecriture',
            name='tiers',
            field=models.ForeignKey(blank=True, help_text='Tiers pour les comptes auxiliaires', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_ecritures', to='accounting.tiers'),
        ),
        migrations.AddIndex(
            model_name='ecriturecomptable',
            index=models.Index(fields=['statut'], name='accounting__statut_940548_idx'),
        ),
        migrations.AddIndex(
            model_name='ligneecriture',
            index=models.Index(fields=['tiers'], name='accounting__tiers_i_4861de_idx'),
        ),
    ]
