# Generated by Django 5.2.1 on 2025-05-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_ecriturecomptable_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteohada',
            name='note',
            field=models.TextField(blank=True, help_text='Notes ou précisions sur le compte', null=True),
        ),
        migrations.AddField(
            model_name='compteohada',
            name='solde_normal',
            field=models.CharField(choices=[('debiteur', 'Débiteur'), ('crediteur', 'Créditeur'), ('variable', 'Variable')], default='debiteur', help_text='Solde normal du compte selon OHADA', max_length=20),
        ),
    ]
