# Generated by Django 5.2.1 on 2025-05-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_compteohada_note_compteohada_solde_normal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteohada',
            name='type',
            field=models.CharField(choices=[('actif', 'Actif'), ('passif', 'Passif'), ('charge', 'Charge'), ('produit', 'Produit')], max_length=20),
        ),
    ]
