# Generated by Django 4.2.7 on 2025-05-10 19:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="adresse email"
                    ),
                ),
                ("first_name", models.CharField(max_length=30, verbose_name="prénom")),
                ("last_name", models.CharField(max_length=150, verbose_name="nom")),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le numéro de téléphone doit être au format: '+999999999'.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="numéro de téléphone",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("COMPANY", "Entreprise ou organisation"),
                            ("ACCOUNTANT", "Expert-comptable"),
                        ],
                        default="COMPANY",
                        max_length=20,
                        verbose_name="type d'utilisateur",
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="actif")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="vérifié"),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="membre du staff"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="date d'inscription",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="dernière connexion"
                    ),
                ),
                (
                    "failed_login_attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="tentatives de connexion échouées"
                    ),
                ),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="verrouillé jusqu'à"
                    ),
                ),
                (
                    "mfa_enabled",
                    models.BooleanField(
                        default=False,
                        verbose_name="authentification à deux facteurs activée",
                    ),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP de dernière connexion"
                    ),
                ),
                (
                    "known_devices",
                    models.JSONField(
                        blank=True, default=list, verbose_name="appareils connus"
                    ),
                ),
                (
                    "login_history",
                    models.JSONField(
                        blank=True, default=list, verbose_name="historique de connexion"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "utilisateur",
                "verbose_name_plural": "utilisateurs",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="nom"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="Les rôles système ne peuvent pas être supprimés",
                        verbose_name="rôle système",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de mise à jour"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="users.role",
                        verbose_name="rôle parent",
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, to="auth.permission", verbose_name="permissions"
                    ),
                ),
            ],
            options={
                "verbose_name": "rôle",
                "verbose_name_plural": "rôles",
            },
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        max_length=255, verbose_name="nom de l'entreprise"
                    ),
                ),
                (
                    "legal_form",
                    models.CharField(max_length=100, verbose_name="forme juridique"),
                ),
                (
                    "tax_id",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="numéro d'identification fiscale",
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="adresse")),
                ("city", models.CharField(max_length=100, verbose_name="ville")),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="code postal"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Bénin", max_length=100, verbose_name="pays"
                    ),
                ),
                (
                    "user_position",
                    models.CharField(
                        max_length=100, verbose_name="fonction dans l'entreprise"
                    ),
                ),
                (
                    "accounting_system",
                    models.CharField(
                        choices=[
                            ("SYSCOHADA", "SYSCOHADA (standard)"),
                            ("SYSBENYL", "SYSBENYL (associations/ONG)"),
                            ("MINIMAL", "Système minimal (TPE)"),
                        ],
                        default="SYSCOHADA",
                        max_length=20,
                        verbose_name="système comptable",
                    ),
                ),
                (
                    "onboarding_completed",
                    models.BooleanField(
                        default=False, verbose_name="configuration initiale terminée"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de mise à jour"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "profil entreprise",
                "verbose_name_plural": "profils entreprises",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="horodatage"),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Création"),
                            ("READ", "Lecture"),
                            ("UPDATE", "Mise à jour"),
                            ("DELETE", "Suppression"),
                            ("LOGIN", "Connexion"),
                            ("LOGOUT", "Déconnexion"),
                            ("PERMISSION", "Changement de permission"),
                            ("CUSTOM", "Action personnalisée"),
                        ],
                        max_length=20,
                        verbose_name="type d'action",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="type d'objet"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="identifiant d'objet"
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="métadonnées"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "journal d'audit",
                "verbose_name_plural": "journaux d'audit",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AccountantProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firm_name",
                    models.CharField(max_length=255, verbose_name="nom du cabinet"),
                ),
                (
                    "professional_id",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="numéro d'agrément professionnel",
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="adresse")),
                ("city", models.CharField(max_length=100, verbose_name="ville")),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="code postal"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Bénin", max_length=100, verbose_name="pays"
                    ),
                ),
                (
                    "syscohada_certified",
                    models.BooleanField(
                        default=False, verbose_name="certifié SYSCOHADA"
                    ),
                ),
                (
                    "sysbenyl_certified",
                    models.BooleanField(
                        default=False, verbose_name="certifié SYSBENYL"
                    ),
                ),
                (
                    "minimal_certified",
                    models.BooleanField(
                        default=False, verbose_name="certifié Système minimal"
                    ),
                ),
                (
                    "onboarding_completed",
                    models.BooleanField(
                        default=False, verbose_name="configuration initiale terminée"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de mise à jour"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accountant_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "profil expert-comptable",
                "verbose_name_plural": "profils experts-comptables",
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        blank=True,
                        help_text="Identifiant de l'objet auquel ce rôle s'applique, si applicable",
                        max_length=255,
                        verbose_name="portée",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de mise à jour"
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigné par",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to="users.role",
                        verbose_name="rôle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "rôle utilisateur",
                "verbose_name_plural": "rôles utilisateurs",
                "unique_together": {("user", "role", "scope")},
            },
        ),
    ]
