# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='code',
            field=models.CharField(default='', help_text='Code technique pour référencer le rôle', max_length=50, unique=True, verbose_name='code'),
            preserve_default=False,
        ),
    ]