# Generated by Django 4.2.7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='action_type',
            new_name='action',
        ),
    ]