# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_action_type_to_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='object_type',
            new_name='resource_type',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='object_id',
            new_name='resource_id',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='description',
            new_name='resource_representation',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='metadata',
            new_name='additional_data',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='user agent'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='identifiant de ressource'),
        ),
    ]