# Generated by Django 5.2.1 on 2025-05-25 08:57

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('tenant_type', models.CharField(choices=[('ENTERPRISE', 'Entreprise individuelle'), ('CABINET', 'Cabinet comptable')], default='ENTERPRISE', max_length=20)),
                ('plan', models.CharField(choices=[('starter', 'Starter - 50 000 XAF/mois'), ('professional', 'Professional - 150 000 XAF/mois'), ('enterprise', 'Enterprise - 350 000 XAF/mois'), ('cabinet_start', 'Cabinet Start - 200 000 XAF/mois'), ('cabinet_pro', 'Cabinet Pro - 500 000 XAF/mois'), ('cabinet_unlimited', 'Cabinet Unlimited - 1 000 000 XAF/mois')], default='starter', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
