# Generated by Django 5.2.1 on 2025-05-25 09:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Fonctionnalité',
                'verbose_name_plural': 'Fonctionnalités',
            },
        ),
        migrations.CreateModel(
            name='PlanLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_type', models.CharField(max_length=30)),
                ('max_users', models.IntegerField(default=5)),
                ('max_enterprises', models.IntegerField(default=1)),
                ('max_ai_calls', models.IntegerField(default=100)),
                ('storage_gb', models.IntegerField(default=5)),
                ('features', models.ManyToManyField(to='tenants.planfeature')),
            ],
            options={
                'verbose_name': 'Limite de plan',
                'verbose_name_plural': 'Limites de plan',
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan_limit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='tenants.planlimit'),
        ),
    ]
