# Generated by Django 5.2.1 on 2025-05-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_planfeature_planlimit_tenant_plan_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise'), ('cabinet_start', 'Cabinet Start'), ('cabinet_pro', 'Cabinet Pro'), ('cabinet_unlimited', 'Cabinet Unlimited')], default='starter', max_length=30),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tenant_type',
            field=models.CharField(choices=[('ENTERPRISE', 'Entreprise'), ('CABINET', 'Cabinet comptable')], default='ENTERPRISE', max_length=20),
        ),
    ]
